
  
name: Building TWRP Android 11

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
  DEVICE: phoenix
  DT_LINK: https://github.com/sinister-virus/android_device_xiaomi_surya -b master
  DT_PATH: device/xiaomi/surya
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
            
       - name: Sync TWRP A11 source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST --depth=1 --partial-clone --clone-filter=blob:limit=10M --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -j4
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             
       - name: Building TWRP
         run: |
              cd work
              . build/envsetup.sh &&lunch twrp_$DEVICE-eng 
              repo sync -j4
              export ALLOW_MISSING_DEPENDENCIES=true && mka $TARGET
             
       - name: Uploading recovery image
         run: |
              cd work/out/target/product/$DEVICE
              sudo zip -r9 TWRP-phoenix-a11.zip recovery.img
